### ISSUE TITLE
Request: Chairs can have additional sides along with signs

### ISSUE THREAD

**Issue by LadyCailinBot** [EngineHub/CraftBook#1020]
CRAFTBOOK-3216 - Reported by FrozenBeard

I want to try and replace my dedicated chairs plugin with Craftbook, but the features are limited.
Could you please add the option to set the chair sides as well as what is classed as a chair.
*For example:*
```yaml
valid-signs:
- SIGN
- WALL_SIGN
- SIGN_POST
- ITEM_FRAME
- WALL_BANNER
```

Another option that would be nice, would be to have sit restrictions to disable all commands or specific commands. 
```yaml
sit-restrictions:
  commands:
    all: false
    list:
    - /examplecommand
```

Another option that would be nice would be Item-pickup, allow people to pick up items while sitting or not.

Thank you.
