### ISSUE TITLE
SignCopier mechanic throws out NoCheatPlus auto sign violations.

### ISSUE THREAD

**Issue by LadyCailinBot** [EngineHub/CraftBook#1067]
CRAFTBOOK-3325 - Reported by mibby

CraftBook dev 154
NoCheatPlus dev 111

Using the SignCopier mechanic, players throw out NoCheatPlus block place auto sign violations. Is there any way to prevent this or add compatibility through cncp?

```
    autosign:
      active: true
      skipempty: false
      actions: cancel vl>10 log:autosign:0:12:i cancel
```

https://github.com/EngineHub/CraftBook/commit/a5b3b095a951649825281b6e47aceed3c248d26c#commitcomment-22221425
https://github.com/NoCheatPlus/Issues/issues/451
