### ISSUE TITLE
Custom Recipes: charcoal not available as ingredients

### ISSUE THREAD

**Issue by ZhaoZuohong** [EngineHub/CraftBook#1215]
**Versions**

CraftBook version: Both latest stable(3.10.2;21180b0) and latest dev build(3.10.3-SNAPSHOT;4635-df13f9f)
Bukkit version: paper-131(latest paperspigot)

**Describe the bug**

Custom recipes does not work when charchal is part of the ingredients of the recipes.

**To Reproduce**

1. create a recipe, set charcoal as part of ingredients(see *Additional context* part for a prepared `crafting-recipe.yml` file);
2. launch game and try out.

**Expected behavior**

It is expected that the customized recipe works well.

**Screenshots**

![2020-08-04_18 10 03](https://user-images.githubusercontent.com/34163622/89282233-cdc95000-d67d-11ea-9fba-07d06e28f5db.png)

**Additional context**

A typical `crafting-recipes.yml`:

```yaml
crafting-recipes:
  shapelessexample:
    type: shapeless
    ingredients:
      'minecraft:charcoal': 1
    results:
      'minecraft:cobblestone': 1
```

Actually, charcoal works well if it is specified as part of the result, but unfortunately, when it is part of the ingredients, the recipe does not work.
