### ISSUE TITLE
Custom crafting recipe that has a reversal recipe causes stone to break.

### ISSUE THREAD

**Issue by mibby** [EngineHub/CraftBook#1237]
**Versions**
CraftBook version: 3.10.3-SNAPSHOT dev 4673
Bukkit version: Paper dev 323 (Spigot 1.16.4)
WorldEdit version: 7.2.x dev 5524

**Describe the bug**
If you have a custom crafting recipe that reverses into itself, it breaks the stone crafting recipe for buttons. Instead stone crafts into itself.

```
  coraltube1:
    type: shapeless
    ingredients:
      'tube_coral': 1
    results:
      'dead_tuba_coral': 1
  coraltube2:
    type: shapeless
    ingredients:
      'dead_tuba_coral': 1
    results:
      'tuba_coral': 1
```

**To Reproduce**
1. Add two custom crafting recipes that reverse into each other.
2. Put stone in a crafting table. 
3. Stone no longer crafts into a button; it's effectively broken. Stone -> Stone

**Expected behavior**
Stone to work and craft into stone buttons.

**Additional context**
Removing one of the recipes fixes stone, but then the custom recipe doesn't work. Changing the recipe requirements (such as amount) of one of them fixes stone as well, but then it's not a 1:1 crafting ratio.
