### ISSUE TITLE
ICs Shorthand seems not to work?

### ISSUE THREAD

**Issue by CloudeLecaw** [EngineHub/CraftBook#1262]
> Shorthand
> Shorthand is a way of creating IC’s, without having to remember the ID. Instead of putting [MCXXXX] on the 2nd line, put =shorthand on the first. Eg, for a repeater enter =repeater on the first line.

mechanisms.yml
```
    ICs:
        cache: true
        max-radius: 10.0
        allow-short-hand: true
```

Looks like the shorthand is not working =(

![Snag_d06b906](https://user-images.githubusercontent.com/12080017/114796756-f9b2de80-9d91-11eb-89cc-39134f03547a.png)
![Snag_d06fae2](https://user-images.githubusercontent.com/12080017/114796769-033c4680-9d92-11eb-9c82-19f65251ed58.png)

CraftBook_3.10.4-Build4700
PaperMC 1.16.5
