### ISSUE TITLE
vehicles print / messenger signs are silent

### ISSUE THREAD

**Issue by LadyCailinBot** [EngineHub/CraftBook#649]
CRAFTBOOK-2711 - Reported by andy.armanini

I can place a [print] sign with a message under the appropriate block with rails on top, and the system tells me that it has been created, but when a player runs over it no text is shown in chat. All other cart signs function correctly.

CraftBook build 3207 on Spigot-1070

```yaml|title=config.yml
vehicles:
    minecart:
        decay-when-empty:
            enable: false
            time-in-ticks: 20
        mechanisms:
...
            messager:
                enable: true
                block: '159:6'
```
